### ISSUE TITLE
Not working - Events changed

### ISSUE THREAD

**Issue by macr1408** [macr1408/Whatsapp-scripts#5]
Text input (message) changed, now it doesn't do any single thing when the events are fired!

I couldn't see any event listener, tried with anything (keyup, keydown, input) and nothing works. I ran out of ideas.

and btw, some elements changed their classes (these are the new lines that you should add):

```
var input = document.getElementsByClassName("input-container")[0];
document.querySelector(".compose-btn-send > span").click(); 
```

**Comment by ajeetsonijeet** [comment]
Plz i reqst you sir
Give me add creat script
I am not addting this 2 line
Plz give me confram script 
Plz  i  request you plz
Help me plz

**Comment by divyamrajput** [comment]
Sir please check this issue and make a proper solution i want to spam and i am also a big fan of your.please sir check this problem and solve out this issue soon as soon possible.
Thanks sir .
I hope you will works on it.

**Comment by sudeepsingh2108** [comment]
Sir can you edit that script 
we can't write that on old script

**Comment by macr1408** [comment]
Guys the script is not working, those lines won't make it to work again, please read carefully. 

Be patient until a fix is released (it could be days or weeks, or years, or never, just wait)

-Macr1408

**Comment by divyamrajput** [comment]
Okay sir please make a good script for us as soon as possible.

**Comment by inxomnyaa** [comment]
Working on Fixing it.

**Comment by macr1408** [comment]
Working again, enjoy

**Comment by divyamrajput** [comment]
Thankuuu so much sir.
God bless you.
Sir i am now fan of you sir.
Thankyouuuuuuuu sirrrrr.
Sir thankxx

**Comment by divyamrajput** [comment]
NOT WORKING PLEASE CHECK IT AND MAKE SCRIPT WORKING
