### ISSUE TITLE
Rewrite for jQuery

### ISSUE THREAD

**Issue by inxomnyaa** [macr1408/Whatsapp-scripts#6]
I'd suggest a rewrite in jQuery. Reason: you can update inputs easier, and the code should become cleaner. Also cloning/duplicating elements (for example the send button) is easier too.

I'd totally do the rewrite myself if you'd like.

**Comment by macr1408** [comment]
jQuery doesn't exist in whatsapp web, check it by yourself

```
if (window.jQuery) {  
    console.log("jQuery is loaded!");
} else {
    console.log("jQuery is not loaded :(");
}

```

And i won't load a full lib only to make it easier to read, sorry but it is a waste of resources.
