### ISSUE TITLE
NOT WORKING

### ISSUE THREAD

**Issue by divyamrajput** [macr1408/Whatsapp-scripts#8]
Please check this script again because it is not working now. Please fixed it.

**Comment by macr1408** [comment]
Fixed

**Comment by divyamrajput** [comment]
THANKS SIR

**Comment by divyamrajput** [comment]
CHECK AGAIN SCRIPT BECAUSE SCRIPT IS NOT RUNNING PROPERLY

**Comment by divyamrajput** [comment]
Messages are not typing please recheck

**Comment by ajeetsonijeet** [comment]
Please check this script again because it is not working now. Please fixed it.

**Comment by divyamrajput** [comment]
Please check this script again
